Issue #13 - returns info about pages
Myra-Security-GmbH/myrasec-go pull request #7
Opened 2021-07-12 11:41 UTC by robertwe

Signed-off-by: robertwe <robert.weclawski@mykolab.com>

2021-07-14 12:45 UTC, xellio requested changes
I do not like this change as the return values are not consistent anymore.
listDomains returns a slice of Domain structs - so listDnsRecords should return a slice of DnsRecord structs and so on.
The Output struct is more or less the same as the Response struct.
Do we need the information about the page, size and count (as it should be the same as what was passed in the params to the function)?

2021-07-14 12:49 UTC, robertwe reviewed
> I do not like this change as the return values are not consistent anymore.
> listDomains returns a slice of Domain structs - so listDnsRecords should return a slice of DnsRecord structs and so on.
> The Output struct is more or less the same as the Response struct.
> Do we need the information about the page, size and count (as it should be the same as what was passed in the params to the function)?

it breaks consistency for sure but I think it make sense to return to the client info about pagaSize and pageNumber. 
In a long term return type should be pretty much consistent - I fully agree with that.
@xellio Please let me know what do you think. This PR is def not a final solution more like a hotfix. Plan is to slowly refactor whole package.

2021-07-15 14:25 UTC, xellio approved these changes

2021-07-15 14:26 UTC, xellio commented
I created a followup task: https://github.com/Myra-Security-GmbH/myrasec-go/issues/8

2021-07-16 07:48 UTC, merged